language: php

cache:
    directories:
        - $HOME/.composer/cache

dist: trusty
sudo: required

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env: SYMFONY_VERSION='2.8.*'
  fast_finish: true

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit
